name: Fetch proxies

on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Combine URL contents
      run: |
        # Replace with your URLs
        URL1="https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/vless"
        URL2="https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/vmess"

        # Fetch the contents
        CONTENT1=$(curl -s "$URL1")
        CONTENT2=$(curl -s "$URL2")

        # Combine and save to a file
        echo -e "$CONTENT1\n$CONTENT2" > input/proxies.txt

    - name: Upload combined content
      uses: actions/upload-artifact@v2
      with:
        name: proxies
        path: input/proxies.txt

    - name: Check for Input Changes
      id: changesin
      run: |
        git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
      
    - name: Commit and push if there are changes
      run: |
      if: steps.changes.outputs.changed == 'true'
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add input/proxies.txt
        git commit -m "Fetch proxies"
        git push
